lint:
  files_exist:
  - CODE_OF_CONDUCT.md
  - assets/nf-core-primeseq_logo_light.png
  - docs/images/nf-core-primeseq_logo_light.png
  - docs/images/nf-core-primeseq_logo_dark.png
  - .github/ISSUE_TEMPLATE/config.yml
  - .github/workflows/awstest.yml
  - .github/workflows/awsfulltest.yml
  - .github/.dockstore.yml
  - .github/workflows/branch.yml
  - .github/workflows/linting_comment.yml
  - conf/test.config
  - conf/test_full.config
  - .github/workflows/ci.yml
  files_unchanged:
  - .github/workflows/linting.yml
  - CODE_OF_CONDUCT.md
  - assets/nf-core-primeseq_logo_light.png
  - docs/images/nf-core-primeseq_logo_light.png
  - docs/images/nf-core-primeseq_logo_dark.png
  - .github/ISSUE_TEMPLATE/bug_report.yml
  multiqc_config:
  - report_comment
  nextflow_config:
  - manifest.name
  - manifest.homePage
nf_core_version: 2.14.1
repository_type: pipeline
template:
  author:
  - Martin Proks
  - Nazmus Salehin
  description: PRIME-seq preprocessing pipeline
  name: primeseq
  prefix: brickmanlab
